# Generated by Django 5.0.6 on 2024-06-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_img', models.ImageField(upload_to='car_images/')),
                ('car_title', models.CharField(max_length=100)),
                ('car_description', models.TextField()),
                ('car_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
