# Generated by Django 5.0.6 on 2024-06-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_img',
            field=models.ImageField(upload_to='add_car/media/car_images/'),
        ),
    ]
