# Generated by Django 5.0.6 on 2024-06-16 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_car', '0003_car_brands'),
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brands',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brands.brands'),
        ),
    ]
