# Generated by Django 5.0.6 on 2024-06-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_car', '0004_alter_car_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
