# Generated by Django 5.0.6 on 2024-06-19 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_remove_purchase_car_remove_purchase_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
